analysis:
    resource: "@AnalysisBundle/Resources/config/routing.yml"
    prefix:   /analysis

seedmetrix_importexcel:
    resource: "@SeedmetrixImportexcelBundle/Resources/config/routing.yml"
    prefix:   /import

