analysis_homepage:
    path:   /
    defaults: { _controller: AnalysisBundle:Default:index }
#    methods: [GET]
#analysis_recherche:
#    path:   /recherche
#    defaults: { _controller: AnalysisBundle:Default:recherche }
#    methods: [POST]